// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL_xWXJc8-2NAniBOwbD4JrFYEH0lYrIM',
    appId: '1:257908888395:web:c9d872a1518b6932c10ece',
    messagingSenderId: '257908888395',
    projectId: 'siparis-uygulamasi-aa507',
    authDomain: 'siparis-uygulamasi-aa507.firebaseapp.com',
    storageBucket: 'siparis-uygulamasi-aa507.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8L7a2PPtOZ2kaGDHEFnCGJhbB2Q7v5k',
    appId: '1:257908888395:android:8c76776c3e8513f2c10ece',
    messagingSenderId: '257908888395',
    projectId: 'siparis-uygulamasi-aa507',
    storageBucket: 'siparis-uygulamasi-aa507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9_EFAwJmWfkz02zfShm_M1qDt76kBsk',
    appId: '1:257908888395:ios:cbeb205fb6da4e91c10ece',
    messagingSenderId: '257908888395',
    projectId: 'siparis-uygulamasi-aa507',
    storageBucket: 'siparis-uygulamasi-aa507.firebasestorage.app',
    iosBundleId: 'com.example.siparisVermeUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9_EFAwJmWfkz02zfShm_M1qDt76kBsk',
    appId: '1:257908888395:ios:cbeb205fb6da4e91c10ece',
    messagingSenderId: '257908888395',
    projectId: 'siparis-uygulamasi-aa507',
    storageBucket: 'siparis-uygulamasi-aa507.firebasestorage.app',
    iosBundleId: 'com.example.siparisVermeUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL_xWXJc8-2NAniBOwbD4JrFYEH0lYrIM',
    appId: '1:257908888395:web:760471dcb07a3d9ac10ece',
    messagingSenderId: '257908888395',
    projectId: 'siparis-uygulamasi-aa507',
    authDomain: 'siparis-uygulamasi-aa507.firebaseapp.com',
    storageBucket: 'siparis-uygulamasi-aa507.firebasestorage.app',
  );
}
